### ISSUE TITLE
Disclose BigTable Costs in Readme

### ISSUE THREAD

**Issue by garymazz** [ofek/pypinfo#105]
After spending a bunch of time setting up the GCP account, and looking at usage, it seems to be very expensive. 

After the free tier is consumed and the 90day $300 credit expires, **BigQuery costs $5 per TB of data queried**. Querying the `simple_requests` table which is 49.77 TB would cost **$250 per query**. 

A query of the `distribution_metadata` table (18.8GB) would cost **$0.094 per query**. Again very expensive.. 

Placing the data in AWS S3 using S3  Select cost about the same, still very expensive.   

I think this should be fully disclosed in the readme file

**Comment by tswast** [comment]
These costs got significantly reduced by https://github.com/ofek/pypinfo/pull/107 which uses the clustered tables.

**Comment by hugovk** [comment]
Yes, that made a huge difference, thanks!

The README has example queries showing costs (PR welcome to rerun and update the data use/estimated cost in output!). 

Before this recent improvement, I think the amount of data and therefore cost had been increasing over time, so it would be difficult for us to state the exact cost.

@garymazz Please could you update to the newest release, and if you think it's still necessary, propose a change to the README with the sort of disclosure you had in mind? 

Thanks!

**Comment by hugovk** [comment]
Closing due to lack of response, and usage costs are now significantly reduced.

**Comment by kaos** [comment]
I still think it would be worth mentioning the expected cost of queries, especially when querying over longer time frames.

I was a bit careless and just copied the example SQL from the readme into the BigQuery console, and that cost me $25 for a single query. Ouch. (I didn't pay too much attention to the days argument, and was happy with the LIMIT, but it turns out, the LIMIT has no effect on cost as you pay for the amount of data processed, not data returned in the result set)

/me unhappy.

```
$ pypinfo --test --days 365 --limit 100 "" project percent3
```
```sql
SELECT
  file.project as project,
  ROUND(100 * SUM(CASE WHEN REGEXP_EXTRACT(details.python, r"^([^\.]+)") = "3" THEN 1 ELSE 0 END) / COUNT(*), 1) as percent_3,
  COUNT(*) as download_count,
FROM `bigquery-public-data.pypi.file_downloads`
WHERE timestamp BETWEEN TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL -366 DAY) AND TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL -1 DAY)
  AND details.installer.name = "pip"
GROUP BY
  project
ORDER BY
  download_count DESC
LIMIT 100
```
```
Bytes processed
 5.44 TB 
Bytes billed
 5.44 TB 
```

**Comment by hugovk** [comment]
Please could you open a PR with something you think would be helpful? 

Let's reduce the number of days in that example as well.

**Comment by kaos** [comment]
I may be able to write something up next weekend.
