### ISSUE TITLE
Pypinfo Error - 400 FROM clause with table wildcards matches no table

### ISSUE THREAD

**Issue by AV25242** [ofek/pypinfo#114]
Hello,

I have been running pypinfo everymonth to download stats and have had no issues untill April

I started seeing this issue 'google.api_core.exceptions.BadRequest: 400 FROM clause with table wildcards matches no table'

Has the underlying table changed?  Also it logs the below query.

Any guidance ?
```sql
SELECT
file.version as version,
 COUNT(*) as download_count,
FROM
 TABLE_DATE_RANGE(
  [the-psf:pypi.downloads],
  DATE_ADD(CURRENT_TIMESTAMP(), -31, "day"),
 DATE_ADD(CURRENT_TIMESTAMP(), -1, "day")
 )
  WHERE
  file.project = "<myprojectname>"
 AND details.installer.name = "pip"
GROUP BY
 version,
ORDER BY
 download_count DESC
LIMIT 10
```

**Comment by hugovk** [comment]
Google has changed the data table and presumably the old one has now been removed.

Please update to the latest pypinfo, this was fixed in https://github.com/ofek/pypinfo/pull/111 and released in the latest version 19.0.0.

**Comment by AV25242** [comment]
Thanks @hugovk  for the quick response. Let me update to the latest pypinfo.

**Comment by AV25242** [comment]
That worked, closing the issue. Thanks again !
