### ISSUE TITLE
Documentation types are not accurate

### ISSUE THREAD

**Issue by enarroied** [ofek/pypinfo#152]
Hi, 

The documentation states that:

-l, --limit TEXT        
-d, --days TEXT  

But I think it should say INTEGER

**Comment by hugovk** [comment]
The README is out of date, the `--help` shows:

```
  -l, --limit INTEGER     Maximum number of query results. Default: 10
  -d, --days INTEGER      Number of days in the past to include. Default: 30
```

Would you like to create a PR to fix it?

**Comment by enarroied** [comment]
I just created a Pull Request to fix it, I hope it's fine because it is the first time I do it!
