### ISSUE TITLE
Use standard SQL

### ISSUE THREAD

**Issue by ofek** [ofek/pypinfo#28]
https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql

**Comment by jayvdb** [comment]
Is there any reason to not do this?

**Comment by ofek** [comment]
Nope, just not enough time!

**Comment by jayvdb** [comment]
Ok, I'll try this first, and we'll find out if it costs more, then we can try https://github.com/ofek/pypinfo/issues/73.

**Comment by tswast** [comment]
This was fixed in https://github.com/ofek/pypinfo/pull/107

**Comment by ofek** [comment]
Thanks!
