### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by evyatarmeged** [ofek/pypinfo#39]
Any known reason why or how the total download count could decrease between calls ? I've had my download count drop more than once on different `pypinfo` calls a few days apart from each other.

**Comment by hugovk** [comment]
The defaults are to check the downloads of the previous 30 days. 

For example:
```
aaaaxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxbbbb
```

The downloads during the `a` days could be more than the downloads during the `b` days.

**Comment by ofek** [comment]
@hugovk is correct; a moving windowed total is expected to change :)

**Comment by evyatarmeged** [comment]
Alright, thanks guys.
