### ISSUE TITLE
wrong installation hints

### ISSUE THREAD

**Issue by nschloe** [ofek/pypinfo#6]
> This is relatively painless, I swear.

Well...

>  During creation, choose BigQuery User as role. 

First off, which of

 * API key
 * OAuth client ID
 * Service accout key

do I choose? I suppose _Service account key_ since this is the only one that takes me to another screen with _role_ in it. There's no such rule as _BigQuery User_ however.

**Comment by ofek** [comment]
In [link for step 4](https://cloud.google.com/storage/docs/authentication#generating-a-private-key) it says `3. Select Service account key.`.

**Comment by ofek** [comment]
@nschloe You don't see this?

![gcp](https://user-images.githubusercontent.com/9677399/29724043-07e0c81a-8995-11e7-9c75-dfaf700f29fb.PNG)

**Comment by ofek** [comment]
@nschloe Is it working for you now?

**Comment by nschloe** [comment]
No, I don't see BigQuery:

![bq](https://user-images.githubusercontent.com/181628/29740772-6f6e2fda-8a5e-11e7-9396-dc024bde8218.png)

**Comment by nschloe** [comment]
Okay, I removed all accounts and keys and started all over. It appears to work now.

**Comment by bskinn** [comment]
@nschloe Did you previously have Google Cloud accounts? I encountered the same thing, where BigQuery didn't show in the Roles list, and I had a G Cloud account from a year and a half or so lying around.

**Comment by nschloe** [comment]
@bskinn Indeed.

**Comment by bskinn** [comment]
@nschloe Weirdly, BigQuery [showed up in the Roles list](https://github.com/ofek/pypinfo/issues/7#issuecomment-330663365) for the project permissions after a while.

Maybe it just takes G Cloud longer to propagate all the possible roles into a new project, if an old project already existed in the overall G Cloud account?

Is weird.  Got it working, though - woot!
