### ISSUE TITLE
Target for "Generating a Private Key" is missing

### ISSUE THREAD

**Issue by tomduck** [ofek/pypinfo#60]
Hi there.  The installation instructions in your README includes the following link in step 5:

https://cloud.google.com/storage/docs/authentication#generating-a-private-key

This target does not appear to exist.  As such, I am unsure how to "create credentials in JSON format."

Thanks,
Tom

**Comment by ofek** [comment]
Hmm, thanks! Maybe they moved it here? https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys

cc @hugovk

**Comment by hugovk** [comment]
I set up a new one only a couple of weeks ago, and didn't notice anything much different from the instructions, though the Google interface is not that welcoming.

But that looks about right. I could get to the "Create key" > JSON step with this:


---

![image](https://user-images.githubusercontent.com/1324225/47171906-a96a7b00-d312-11e8-8743-4510bd42eb3b.png)

**Comment by hugovk** [comment]
I just created a new project and got the JSON. Do these steps help?


# Create project

Create a project at https://console.developers.google.com/cloud-resource-manager

> ![image](https://user-images.githubusercontent.com/1324225/47172949-6f4ea880-d315-11e8-8587-8b8117efeae9.png)

---

Goes to https://console.developers.google.com/projectcreate

---

> ![image](https://user-images.githubusercontent.com/1324225/47173020-986f3900-d315-11e8-90ab-4b2ecd85b88e.png)

---

Fill in and click create. The next page showed my old project, but reloading let me select it from the top menu:

https://console.developers.google.com/home/dashboard?project=test-project--219817

---

> ![image](https://user-images.githubusercontent.com/1324225/47173170-0b78af80-d316-11e8-879e-01f34e139b80.png)

---

# Enable BigQuery API

Go to https://console.cloud.google.com/apis/api/bigquery-json.googleapis.com/overview and check the correct project is shown, and enable the API:

---

> 	![image](https://user-images.githubusercontent.com/1324225/47173408-a6718980-d316-11e8-94c2-a17ff54fc389.png)

---

After enabling, click "CREATE CREDENTIALS":

---

> ![image](https://user-images.githubusercontent.com/1324225/47173432-bc7f4a00-d316-11e8-8152-6a0e6cfab70f.png)

---

Choose BigQuery and No:

---

> ![image](https://user-images.githubusercontent.com/1324225/47173510-ec2e5200-d316-11e8-8508-2bfbb8f6b02f.png)

---

Fill in the name and role and JSON:

> ![image](https://user-images.githubusercontent.com/1324225/47173576-18e26980-d317-11e8-8bfe-e4775d965e32.png)

---

Click continue and the JSON will download to your computer:

---

> ![image](https://user-images.githubusercontent.com/1324225/47173614-331c4780-d317-11e8-9ed2-fc76557a2bf6.png)

---

**Comment by tomduck** [comment]
It works!  Thank you.  I am grateful for this help.

There is only one step that I had trouble with.  When I created the project, there was no way I could find to get to the "dashboard" that you show.  Instead, I was on the "IAM" screen.  No matter.  I was able to complete the rest of the steps regardless.

**Comment by ofek** [comment]
@hugovk Thank you very much! Pretty please can you submit a PR to update the docs? 🙏

**Comment by tomduck** [comment]
Will do.

**Comment by Andre0512** [comment]
Please update! I tried the readme and it took me a while to find this.

**Comment by hugovk** [comment]
Will do, in the meantime here's a very quick PR to temporarily link the README to https://github.com/ofek/pypinfo/issues/60#issuecomment-431102204.
