### ISSUE TITLE
new option start-month (or: allow incomplete date YYYY-MM)

### ISSUE THREAD

**Issue by thorade** [ofek/pypinfo#61]
This is possibly related to #47 as well as #48.

I would like to have statistics for each month, and this is achievable throught `--start-date` and `--end-date` options, but for convenience it would be nice to be able to just specify the month like 2018-10. 

This could be either done using a new option `--start-month` or by allowing a start-date without the DD, that is automatically extended to first day of the month when used for start-date and to last day of the month when used as end-date.
For both ways, start-month or incomplete start-date, the end-month or end-date should be automatically set to the (last day of the) same month by default, but changeable by the user.

Does this make sense?

**Comment by hugovk** [comment]
> by allowing a start-date without the DD, that is automatically extended to first day of the month when used for start-date and to last day of the month when used as end-date.

Sounds useful to me. 

> For ... incomplete start-date, the ... end-date should be automatically set to the (last day of the) same month by default, but changeable by the user.

So if start-date is 2018-10, end-date would be set to 2018-10/2018-10-31?

And in other cases, if start-date is 2018-10-01 or -5, end-date is left to the default?

**Comment by thorade** [comment]
Yes, I think you have it exactly right. So, the end-date default would depend on the start-date format. Not sure whether that is nice.

**Comment by hugovk** [comment]
Please see PR #71 which lets you do this:

```console
$ pypinfo --test --start-date 2018-04-01 --end-date 2018-04-30 setuptools
$ pypinfo --test --start-date 2018-04 --end-date 2018-04 setuptools
$ pypinfo --test --month 2018-04 setuptools
```
