### ISSUE TITLE
Use clustered BigQuery tables for 95% improvements in querying costs

### ISSUE THREAD

**Issue by fhoffa** [ofek/pypinfo#64]
I create daily new tables that heavily improve the costs of going to BigQuery. `pypinfo` could use them:

- https://towardsdatascience.com/python-pypi-stats-in-bigquery-reclustered-d80e583e1bfe

(goes from 200GB queries to 10GB queries)

**Comment by tswast** [comment]
This schema is now used for the official tables. I've updated the guide here: https://packaging.python.org/guides/analyzing-pypi-package-downloads/

Most queries required only minor changes to use the new `file_downloads` table and filter by the `timestamp` partition column.

**Comment by ofek** [comment]
@tswast Thanks for the bump! Would you be open to making a PR? 🙂
