### ISSUE TITLE
Service account credentials & BigQuery API activation instructions appear out of date

### ISSUE THREAD

**Issue by bskinn** [ofek/pypinfo#7]
I think the README instructions on enabling BigQuery for the service account are out of date.  I didn't see any way to activate BigQuery access during the credential generation process.

As best I can tell, what worked for me was setting the following in the Google Cloud project settings:

1) In `IAM & Admin` > `IAM`, add the newly created service account/credential to the permissions list, and give it `Owner` permissions
2) In "APIs & Services" > "Dashboard", click `ENABLE APIS AND SERVICES`, select `BigQuery API` from the list, and click `ENABLE`

**Comment by ofek** [comment]
Please let me know if reading this helps https://github.com/ofek/pypinfo/issues/6

**Comment by bskinn** [comment]
Hmm. I have another G Cloud account on there that I don't want to remove, though, so I wouldn't be able to fully repeat what nschloe did.

I do have it working, though, giving `Owner` permissions to the credential is probably overkill.

**Comment by bskinn** [comment]
Weird, BigQuery shows up in the Roles list now:

![image](https://user-images.githubusercontent.com/11325439/30613689-0464c116-9d57-11e7-8ded-36b282abaf1b.png)

It wasn't there before.

**Comment by bskinn** [comment]
I'mma call this a `no repro` and stop pestering you.

Thanks much for the reply.

**Comment by ofek** [comment]
@bskinn Can you please try the updated instructions? step 4

**Comment by bskinn** [comment]
Can't repro. BigQuery shows up now both if I try to create a new credential on my current `pypinfo` project, *and* on trying to create a new credential in a new project.

I'm guessing there was just some internal lag on Google's end before BigQuery showed up as a role option.  See #8.
