### ISSUE TITLE
breakdown by installer now shows only pip

### ISSUE THREAD

**Issue by raamana** [ofek/pypinfo#70]
Hi There,

Compared to the results returned in Aug 2018, my trials today with pypinfo returns download count for pip only. Is this expected or a bug? What happened to other installers? how can I get a count that's as comprehensive as possible? Thanks.

Also, what's the easiest/fastest way to obtain all-time download count for a particular package (entire life-time)?

download counts for `neuropredict` package with the command
`pypinfo -sd -400 neuropredict installer` :

Aug 2018
```
| installer_name | download_count |
| -------------- | -------------- |
| bandersnatch   |         14,182 |
| requests       |            262 |
| Browser        |            248 |
| pip            |             87 |
| None           |             66 |
| z3c.pypimirror |             34 |
| Artifactory    |             23 |
| pep381client   |             20 |
| devpi          |              3 |
```

Jan 2019
```
| installer_name | download_count |
| -------------- | -------------- |
| pip            |            241 |
```

**Comment by ofek** [comment]
https://github.com/ofek/pypinfo/pull/51

**Comment by raamana** [comment]
thanks.
