### ISSUE TITLE
Web api availability

### ISSUE THREAD

**Issue by Ruturaj4** [ofek/pypinfo#74]
Is there a web api available?

So, that I can download or query the json directly from there.

Note: I followed all the steps given in the doc to create a bigquery project. I can use the tool on command line and I know that I can use `--json` flag to get the json response.

**Comment by hugovk** [comment]
The web API would be to call Google BigQuery directly.

See https://packaging.python.org/guides/analyzing-pypi-package-downloads/ and its links.
