### ISSUE TITLE
Increase Tests Coverage

### ISSUE THREAD

**Issue by Physsix27** [ofek/pypinfo#77]
Increase test coverage writing test scripts for the rest of the python files missing.
I will be adding tests scripts for 
> - [x] `pypinfo/cli.py`
> - [x] `pypinfo/db.py`
> - [x] `pypinfo/fields.py`

**Comment by gwappo82** [comment]
> Increase test coverage writing test scripts for the rest of the python files missing.
> I will be adding tests scripts for
> 
> > * [ ]  `pypinfo/cli.py`
> > * [ ]  `pypinfo/db.py`
> > * [ ]  `pypinfo/fields.py`

**Comment by ofek** [comment]
https://github.com/ofek/pypinfo/pull/100

**Comment by hugovk** [comment]
Closing this as `cli.py` is intentionally omitted from test coverage, and everything else is at 100%, except `core.py` at 90.21%.

Overall at 94.89%, which is good. Further test coverage welcome, but we don't need an issue to track it.

![image](https://user-images.githubusercontent.com/1324225/135710121-e367c630-3fd8-4c58-8335-c4a0a823fc92.png)

![image](https://user-images.githubusercontent.com/1324225/135710118-3f90c3fe-df1d-4f94-88a9-c803bda5e34e.png)
