### ISSUE TITLE
System Error: Credentials could not be found

### ISSUE THREAD

**Issue by SHREYAS1188** [ofek/pypinfo#95]
Error: Credentials could not be found

![Screenshot (402)](https://user-images.githubusercontent.com/47130139/85359566-3e843500-b534-11ea-8a8b-06e90dfbf694.png)

**Comment by hugovk** [comment]
Did you follow the installation guide?

https://github.com/ofek/pypinfo#installation

**Comment by SHREYAS1188** [comment]
ok got it
